import random
import time
nomes = ['Jack Chan Nascimento','Lula Inacio da Silva','Vladmir Putin','Elon Musk','Isaac Newton','João da Silva Costa','Maria Santos Gonsalvez','Carlos Oliveira Candido','Ana Pereira Luz','Luan C.','Paulo Junior Guei','luiz Fernando Rocha','Richard Pinto da Silva','Daniel Paladini','Vitor halland Santos']
bancos = ['Banco-Brasil','ITAÙ','CaiXa','NubanK','Itaú Unibanco','HSBC','Industrial and Commercial Bank of China']
def gerador_de_bins():
    print('BEM VINDO AO:\n\n@$%¨¨¨¨ GeRaDoR de Bins ¨¨¨¨¨%$@\n')
    ##_______________________ Ccc1
    digito= random.randint(0,7)
    digito1 = random.randint(0,7)
    digito2 = random.randint(0,9)
    digito3 = random.randint(0,7)
    digito4 = random.randint(0,9)
    digito5 = random.randint(0,6)
    digito6 = random.randint(0,9)
    digito7 = random.randint(0,9)
    digito8 = random.randint(0,5)
    digito9 = random.randint(0,8)
    digito10 = random.randint(0,9)
    digito11 = random.randint(0,9)
    digito12 = random.randint(0,4)
    digito13 = random.randint(0,5)
    digito14 = random.randint(0,6)
    digito15 = random.randint(0,9)
    ##______________________________Ccc2
    digito17 = random.randint(0,4)
    digito18 = random.randint(0,9)
    digito19 = random.randint(0,5)
    digito20 = random.randint(0,9)
    digito21 = random.randint(0,6)
    digito22 = random.randint(0,3)
    digito23 = random.randint(0,6)
    digito24 = random.randint(0,7)
    digito25 = random.randint(0,8)
    digito26 = random.randint(0,9)
    digito27 = random.randint(0,5)
    digito28 = random.randint(0,6)
    digito29 = random.randint(0,8)
    digito30 = random.randint(0,9)
    digito31 = random.randint(0,4)
    digito32 = random.randint(0,5)
    ##_____________________________Ccc3
    digito33 = random.randint(0,4)
    digito34 = random.randint(0,9)
    digito35 = random.randint(0,5)
    digito36 = random.randint(0,9)
    digito37 = random.randint(0,6)
    digito38 = random.randint(0,3)
    digito39 = random.randint(0,6)
    digito40 = random.randint(0,7)
    digito41 = random.randint(0,8)
    digito42 = random.randint(0,9)
    digito43 = random.randint(0,5)
    digito44 = random.randint(0,6)
    digito45 = random.randint(0,8)
    digito46 = random.randint(0,9)
    digito47 = random.randint(0,4)
    digito48 = random.randint(0,5)
    ##_____________________________Ccc4
    digito49 = random.randint(0,4)
    digito50 = random.randint(0,9)
    digito51 = random.randint(0,5)
    digito52 = random.randint(0,9)
    digito53 = random.randint(0,6)
    digito54 = random.randint(0,3)
    digito55 = random.randint(0,6)
    digito56 = random.randint(0,7)
    digito57 = random.randint(0,8)
    digito58 = random.randint(0,9)
    digito59 = random.randint(0,5)
    digito60 = random.randint(0,6)
    digito61 = random.randint(0,8)
    digito62 = random.randint(0,9)
    digito63 = random.randint(0,4)
    digito64 = random.randint(0,5)
    ##_____________________________Ccc5
    digito65 = random.randint(0,4)
    digito66 = random.randint(0,9)
    digito67 = random.randint(0,5)
    digito68 = random.randint(0,9)
    digito69 = random.randint(0,6)
    digito70 = random.randint(0,3)
    digito71 = random.randint(0,6)
    digito72 = random.randint(0,7)
    digito73 = random.randint(0,8)
    digito74 = random.randint(0,9)
    digito75 = random.randint(0,5)
    digito76 = random.randint(0,6)
    digito77 = random.randint(0,8)
    digito78 = random.randint(0,9)
    digito79 = random.randint(0,4)
    digito80 = random.randint(0,5)
    ##_____________________________Acc1
    agencia = random.randint(0,4)
    agencia2 = random.randint(0,6)
    agencia3 = random.randint(0,8)
    agencia4 = random.randint(0,3)
    ##____________________________Acc2
    agencia5 = random.randint(0,7)
    agencia6 = random.randint(0,9)
    agencia7 = random.randint(0,3)
    agencia8 = random.randint(0,7)
    ##____________________________Acc3
    agencia9 = random.randint(0,6)
    agencia10 = random.randint(0,2)
    agencia11 = random.randint(0,5)
    agencia12 = random.randint(0,6)
    ##_____________________________Acc4
    agencia13 = random.randint(0,4)
    agencia14 = random.randint(0,2)
    agencia15 = random.randint(0,4)
    agencia16 = random.randint(0,9)
    ##_____________________________Acc5
    agencia17 = random.randint(0,8)
    agencia18 = random.randint(0,7)
    agencia19 = random.randint(0,4)
    agencia20 = random.randint(0,2)
    ##_____________________________Pcc1
    n_tras1 = random.randint(0,3)
    n_tras2 = random.randint(0,5)
    n_tras3 = random.randint(0,4)
    ##_______________________________Pcc2
    n_tras4 = random.randint(0,9)
    n_tras5 = random.randint(0,2)
    n_tras6 = random.randint(0,7)
    ##______________________________Pcc3
    n_tras7 = random.randint(0,5)
    n_tras8 = random.randint(0,7)
    n_tras9 = random.randint(0,6)
    ##______________________________Pcc4
    n_tras10 = random.randint(0,9)
    n_tras11 = random.randint(0,6)
    n_tras12 = random.randint(0,2)
    ##_____________________________Pcc5
    n_tras13 = random.randint(0,4)
    n_tras14 = random.randint(0,6)
    n_tras15 = random.randint(0,7)
    ##_______________________________N° de cartoes Criados. == variaveis de bancos.
    banco = random.choice(bancos)
    banco2 = random.choice(bancos)
    banco3 = random.choice(bancos)
    banco4 = random.choice(bancos)
    banco5 = random.choice(bancos)
    ##______________________________NOMES:
    nome = random.choice(nomes)
    nome2 = random.choice(nomes)
    nome3 = random.choice(nomes)
    nome4 = random.choice(nomes)
    nome5 = random.choice(nomes)
    
    user = input("digite 'gerarBINs' : ")
    gerar_bin = user.lower
    print("Sucesso...")
    time.sleep(1.5)
    print("Gerando BINs.\n")
    time.sleep(0.5)
    print("Gerando BINs..\n")
    time.sleep(0.5)
    print("Gerando BINs...\n")
    print('----------------')
    
    if user == 'gerarbins':
        print('NOME:',nome,'\n cc1= ',digito,digito1,digito2,digito3,"-",digito4,digito5,digito6,digito7,"-",digito8,digito9,digito10,digito11,"-",digito12,digito13,digito14,digito15)
        print('##                     CVV: ', n_tras1,n_tras2,n_tras3,'  //BANCO:',banco,'\nAGÊNCIA:',agencia,agencia2,agencia3,agencia4,'\n------------------------------------------------\n')
        time.sleep(1)
        print('NOME:',nome2,'\n cc2= ',digito17,digito18,digito19,digito20,"-",digito21,digito22,digito23,digito24,"-",digito25,digito26,digito27,digito28,"-",digito29,digito30,digito31,digito32)
        print('##                     CVV: ', n_tras4,n_tras5,n_tras6,'  //BANCO:',banco2,'\nAGÊNCIA:',agencia5,agencia6,agencia7,agencia8,'\n------------------------------------------------\n')
        time.sleep(1.5)
        print('NOME:',nome3,'\n cc3= ',digito33,digito34,digito35,digito36,"-",digito37,digito38,digito39,digito40,"-",digito41,digito42,digito43,digito44,"-",digito45,digito46,digito47,digito48)
        print('##                     CVV: ', n_tras7,n_tras8,n_tras9,'  //BANCO:',banco3,'\nAGÊNCIA:',agencia9,agencia10,agencia11,agencia12,'\n------------------------------------------------\n')
        time.sleep(1)
        print('NOME:',nome4,'\n cc4= ',digito49,digito50,digito51,digito52,"-",digito53,digito54,digito55,digito56,"-",digito57,digito58,digito59,digito60,"-",digito61,digito62,digito63,digito64)
        print('##                     CVV: ', n_tras10,n_tras11,n_tras12,'  //BANCO:',banco4,'\nAGÊNCIA:',agencia13,agencia14,agencia15,agencia16,'\n------------------------------------------------\n')    
        time.sleep(1.5)
        print('NOME:',nome5,'\n cc5= ',digito65,digito66,digito67,digito68,"-",digito69,digito70,digito71,digito72,"-",digito73,digito74,digito75,digito76,"-",digito77,digito78,digito79,digito80)
        print('##                     CVV: ', n_tras13,n_tras14,n_tras15,'  //BANCO:',banco5,'\nAGÊNCIA:',agencia17,agencia18,agencia19,agencia20,'\n------------------------------------------------\n')
    else:
        print("Quer gerar CC e nem sabe digitar 'gerarBINS'.\n :( ") 
    
    input('Pressione ENTER para Gerar outras BINS...\n__________________________________________________________________')
    gerador_de_bins()

gerador_de_bins()
